// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1764386516);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1764386516);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1764386516);
user_pref("app.update.lastUpdateTime.region-update-timer", 1764040714);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1764386516);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1764386516);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1764042018);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1764386516);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{e4b764a7-e34b-433c-9bbd-5acd92b70bd1}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1764040683);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 140);
user_pref("browser.newtabpage.activity-stream.impressionId", "{487521f1-676a-4448-9422-18aa427927c6}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1764041957);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1764386487287");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1764388261287");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1764386488984");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1764408088984");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20231027194405");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1764386486");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20231027194405");
user_pref("browser.startup.homepage_override.mstone", "119.0");
user_pref("browser.startup.lastColdStartupCheck", 1764386486);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.topsites.contile.cacheValidFor", 11851);
user_pref("browser.topsites.contile.cachedTiles", "[]");
user_pref("browser.topsites.contile.lastFetch", 1764387688);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("browser.urlbar.tipShownCount.searchTip_onboard", 4);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1764040776665");
user_pref("distribution.fedora.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "119.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "IN");
user_pref("dom.push.userAgentID", "6f59eb871b9e482dbafbe987b38da581");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1764386517);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20231027194405");
user_pref("extensions.lastAppVersion", "119.0");
user_pref("extensions.lastPlatformVersion", "119.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"8f0f592c-64b4-4067-aa5a-ff8f120b3ab3\",\"pictureinpicture@mozilla.org\":\"93396983-f16b-42ce-99a3-dae0e4597256\",\"screenshots@mozilla.org\":\"df9e29fd-3e6b-4d9c-bc1e-79667982b15d\",\"webcompat-reporter@mozilla.org\":\"31bf7cfc-d19c-4bfe-81ba-26755b3cc4c5\",\"webcompat@mozilla.org\":\"9537501c-6c7a-4b2d-bcb0-d8f0cee9ff9f\",\"default-theme@mozilla.org\":\"c133ea69-1b2f-4699-ba2a-e37de082d6f1\",\"addons-search-detection@mozilla.com\":\"576ce8d7-1a71-475b-83e6-0793c8dcb703\",\"google@search.mozilla.org\":\"cefb9fcf-7f58-4e2c-b471-d87065e52796\",\"wikipedia@search.mozilla.org\":\"71b6733e-c28d-4dcf-a85c-021c1caf96fc\",\"bing@search.mozilla.org\":\"54a2866a-50fc-4f91-8e32-be6048e7dc91\",\"ddg@search.mozilla.org\":\"88da4ee6-78e9-4511-9f84-435ae95d2acf\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("layout.css.prefers-color-scheme.content-override", 0);
user_pref("media.gmp-manager.buildID", "20231027194405");
user_pref("media.gmp-manager.lastCheck", 1764386771);
user_pref("media.gmp-manager.lastEmptyCheck", 1764386771);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "0ad4564c-3fd9-461f-bffd-26fc41eea520");
user_pref("services.settings.clock_skew_seconds", 590);
user_pref("services.settings.last_update_seconds", 1764386931);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1764386931);
user_pref("services.settings.main.devtools-devices.last_check", 1764386931);
user_pref("services.settings.main.hijack-blocklists.last_check", 1764386931);
user_pref("services.settings.main.language-dictionaries.last_check", 1764386931);
user_pref("services.settings.main.password-recipes.last_check", 1764386931);
user_pref("services.settings.main.sites-classification.last_check", 1764386931);
user_pref("services.settings.main.translations-identification-models.last_check", 1764386931);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("toolkit.startup.last_success", 1764386485);
user_pref("toolkit.telemetry.cachedClientID", "4378b1fa-152e-44e4-a9c3-bafa3c28774a");
user_pref("toolkit.telemetry.previousBuildID", "20231027194405");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
